languageCode = "en"
languageName = "English"
weight = 1
title = "Blue oyster cult"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "新闻学大三学生，未来卵客记者"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Blue Oyster Cult"
  image = "img/blowfish_logo.png"
  headline = "新闻学大三学生，未来卵客记者"
  bio = "新闻学大三学生，未来卵客记者"
  links = [
    { twitter = "https://twitter.com/burufugu" },
    { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://githubfast.com/nunocoracao/blowfish" },
  ]

  
