languageCode = "en"
languageName = "English"
weight = 1
title = "Model United Nations Of NMU"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "18 December 2023"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "President of Model United Nations,Journalism Class 2"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Ravan Zhang"
  image = "img/blowfish_logo.png"
  headline = "新闻学大三学生"
  bio = "President of Model United Nations,Journalism Class 2"
  links = [
    { twitter = "https://twitter.com/burufugu" },
    { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]

  
